### ISSUE TITLE
Phase values for non-significant coherence analyses

### ISSUE THREAD

**Issue by bellaxuying** [JaneliaSciComp/Groundswell#1]
Hi! Not sure if this is still getting actively developed, but I'm wondering if there's a way to view the phase value (in degrees) for non-significant coherence analyses at one frequency? The output results that get automatically copied to clipboard only have specific phase values for significant results, and others have "NaN" - I was wondering if it's possible to make these visible? Or a way to get the values from the output circular plot? Thanks!

**Comment by adamltaylor** [comment]
So the code that replaces those values with nans is in the file

+groundswell/@Controller/coherency_at_f_probe.m

at line 353.  Humorously, shortly after that point there's this comment:

    % if coherency mag is not significant, don't report the phase
    % this was in response to a specific request from Stefan

So, kinda funny.

I don't really have time right now to add this feature in a 'real' way (like adding a place in the UI to choose 'Stefan mode' or 'Bella mode'), but you can hack the source code to achieve this.  Just change line 353 from:

  if Cyx_mag_probe(k)>Cyx_mag_thresh

to

  if true

and then the clipboard text should be how you want it.
